version: '3'

tasks:
  format:
    cmds:
      - crystal tool format
      - bin/ameba
  docs:
    cmd: crystal docs -o api
  test:
    cmd: crystal spec -p
  pull:
    cmd: git pull origin main --rebase
