on:
  push:
    branches: [ "main" ]
  pull_request:
  schedule:
  - cron: '0 6 * * 6'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        crystal: [ "1.14", "1.15", "1.16", "1.17", latest, nightly ]
    runs-on: ubuntu-latest
    steps:
    - name: Download source
      uses: actions/checkout@v4
    - name: Install Crystal
      uses: crystal-lang/install-crystal@v1
      with:
        crystal: ${{ matrix.crystal }}
    - name: Install shards
      run: shards install --ignore-crystal-version
    - name: Check formatting
      run: bin/ameba
    - name: Run tests
      run: crystal spec --order=random
