on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  check_format:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Format
        run: crystal tool format --check
  coding_standards:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: shards install
      - name: Ameba
        run: ./bin/ameba
  test_latest:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: apk add --update jq
      - name: Build
        run: shards build --production
      - name: Specs
        run: crystal spec --order random --error-on-warnings
  test_nightly:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:nightly-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: apk add --update jq
      - name: Build
        run: shards build --production
      - name: Specs
        run: crystal spec --order random --error-on-warnings