on:
  push:
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
      - uses: actions/checkout@v4
      - name: Install Crystal
        uses: shards install
      - name: Check formatting
        run: ./bin/ameba
      - name: Run tests
        run: crystal spec