on:
  push:
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 6 * * 6'

jobs:
  linux-build:
    strategy:
      fail-fast: false
      matrix:
        crystal: ["1.14", "1.15", "1.16", latest, nightly]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download source
        uses: actions/checkout@v4
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
      - name: Install shards
        run: shards install --ignore-crystal-version
      - name: Run tests
        run: crystal spec --order=random
      - name: Check formatting
        run: crystal tool format
      - name: Run Ameba (static analysis)
        uses: crystal-ameba/github-action@v0.12.0